### ISSUE TITLE
Help for disabled-packages in termux

### ISSUE THREAD

**Issue by ashutoshmaurya1122** [xeffyr/termux-makepkg#2]
Can you provide me way to compile termux disabled packages using makepkg. I modified build.sh but not get success.I need openjdk-9-jre -headless

**Comment by xeffyr** [comment]
👉 OpenJDK for Android/Termux can't be built by using clang.

👉 To build OpenJDK in Termux, you need to have OpenJDK installed.

👉 Building OpenJDK in Termux will blow your device - very high ram requirements.

👉 Termux-makepkg has no relation to [termux-packages](https://github.com/termux/termux-packages) or [disabled-packages](https://github.com/termux/termux-packages/tree/master/disabled-packages). It's completely different build system suitable only for Termux.

👉 I am not a help desk so I cannot `provide a way to compile termux disabled packages`.

After reading this message, you will realize, that issue actually with package and not with termux-makepkg. Closing.
