### ISSUE TITLE
problems when compiling bash 5.0 beta2

### ISSUE THREAD

**Issue by d3nish** [xeffyr/termux-makepkg#3]
Hi, I'm trying to compile bash 5.0 beta2 for termux but it crashes while testing. May you have a look on it?
Here is some configs and patches I used.
https://transfer.sh/ndGf9/bash-5.0-beta2-termux.zip

**Comment by 0xXA** [comment]
> Hi, I'm trying to compile bash 5.0 beta2 for termux but it crashes while testing. May you have a look on it?
> Here is some configs and patches I used.
> https://transfer.sh/ndGf9/bash-5.0-beta2-termux.zip

Provide a log?
How was the crash?
Describe the conditions.
Moreover, why do you still name that package as "bash" why not "bash-beta" or something?
I know the regex 
https://github.com/xeffyr/termux-makepkg/blob/master/termux-makepkg#L472
Don't permit that but it's easy to match "-", "_" also.
Looks like script matches only "." between two patters this exception can be removed with a pull

**Comment by d3nish** [comment]
Actually, I build it successful but at the time of testing it crashed idk why it's suddenly crashed so I can't take logs immediately but I'll try to provide
Thanks for solving regex problem tho.

**Comment by xeffyr** [comment]
> at the time of testing it crashed

Some tests may be unsuitable for Termux.

I just have replaced Termux's bash v4 with 5.0/beta, seems okay.
```
$ bash --version
GNU bash, version 5.0.0(1)-beta2 (aarch64-unknown-linux-gnu)
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

> I know the regex
Don't permit that but it's easy to match "-", "_" also.

Main idea was to prevent version values beginning or ending in symbols like "-" or "_".
@0xXA I will merge your PR https://github.com/xeffyr/termux-makepkg/pull/4 for now. But this is not enough.

@d3nish I can add bash5 to package tree.

**Comment by xeffyr** [comment]
>I can add bash5 to package tree.

No, it can't be added. Just got a segfault.

**Comment by 0xXA** [comment]
> Main idea was to prevent version values beginning or ending in symbols like "-" or "_"
@xeffyr I thought you only want prevent at beginning only

What was the result if segfault ?

**Comment by xeffyr** [comment]
@d3nish I found solution. Just add `ac_cv_func_mbsnrtowcs=no` to configure options.
