### ISSUE TITLE
@xeffyr need some info

### ISSUE THREAD

**Issue by d3nish** [xeffyr/termux-makepkg#9]
How can I merge termux-api sources into your all in one source?, Suppose I did it than what to do in termux-api-package ?
I need to edit that package name to what?
@xeffyr

**Comment by d3nish** [comment]
I already told you on telegram you can get commit from my repo which I have done recently, you need to fix this path
https://github.com/termux/termux-api-package/blob/master/termux-api.c#L44

This isn't enough for you, I guess?

**Comment by TheInfected** [comment]
I already told you on telegram you can get commit from my repo which I have done recently, you need to fix this path
https://github.com/termux/termux-api-package/blob/master/termux-api.c#L44

This isn't enough for you, I guess?

**Comment by d3nish** [comment]
Actually, I tried but when I do
```cat somefile | termux-clipboard-set```
It stucks and no output it stucks for infinite time.

```c
child_argv[5] = "com.termux/.TermuxApiReceiver";
```

I used this in termux-api-package with your commit
https://github.com/TheInfected/termux-app/commit/061203a5089b141b946daadebbf7801d14f9e44a
But seems broken :'(
